export const LeadData = [
  {
    id: 1,
    leadName: "Tech Solutions Inc.",
    leadSource: "Website",
    assignedAgent: "Alice Johnson",
    leadStatus: "New",
    tags: ["High Value"],
    timeToClose: 30,
    priority: "High",
    comments: [
      {
        author: "Alice Johnson",
        datetime: "2025-07-12 09:00",
        text: "Initial contact made. Awaiting reply.",
      },
    ],
  },
  {
    id: 2,
    leadName: "Global Innovations Ltd.",
    leadSource: "Referral",
    assignedAgent: "Bob Williams",
    leadStatus: "Contacted",
    tags: ["Follow-up"],
    timeToClose: 45,
    priority: "Medium",
    comments: [
      {
        author: "Bob Williams",
        datetime: "2025-07-10 15:30",
        text: "Follow-up scheduled for next week.",
      },
      {
        author: "Bob Williams",
        datetime: "2025-07-12 11:00",
        text: "Sent email proposal.",
      },
    ],
  },
  {
    id: 3,
    leadName: "Creative Marketing Agency",
    leadSource: "Cold Call",
    assignedAgent: "Alice Johnson",
    leadStatus: "Qualified",
    tags: [],
    timeToClose: 20,
    priority: "High",
    comments: [
      {
        author: "Alice Johnson",
        datetime: "2025-07-09 10:45",
        text: "Lead interested. Qualification complete.",
      },
    ],
  },
  {
    id: 4,
    leadName: "Dynamic Enterprises",
    leadSource: "Website",
    assignedAgent: "Charlie Brown",
    leadStatus: "Proposal Sent",
    tags: ["High Value", "Follow-up"],
    timeToClose: 15,
    priority: "High",
    comments: [
      {
        author: "Charlie Brown",
        datetime: "2025-07-08 13:20",
        text: "Proposal sent. Waiting for response.",
      },
    ],
  },
  {
    id: 5,
    leadName: "Innovate Solutions LLC",
    leadSource: "Referral",
    assignedAgent: "Bob Williams",
    leadStatus: "Closed",
    tags: [],
    timeToClose: 10,
    priority: "Low",
    comments: [
      {
        author: "Bob Williams",
        datetime: "2025-07-01 09:00",
        text: "Deal closed successfully.",
      },
    ],
  },
  {
    id: 6,
    leadName: "Pinnacle Consulting",
    leadSource: "Website",
    assignedAgent: "Charlie Brown",
    leadStatus: "New",
    tags: [],
    timeToClose: 60,
    priority: "Medium",
    comments: [],
  },
  {
    id: 7,
    leadName: "Quantum Tech Group",
    leadSource: "Cold Call",
    assignedAgent: "Alice Johnson",
    leadStatus: "Contacted",
    tags: ["Follow-up"],
    timeToClose: 35,
    priority: "Low",
    comments: [
      {
        author: "Alice Johnson",
        datetime: "2025-07-11 16:00",
        text: "Reached out, waiting for reply.",
      },
    ],
  },
  {
    id: 8,
    leadName: "Bright Future Inc.",
    leadSource: "Website",
    assignedAgent: "Charlie Brown",
    leadStatus: "New",
    tags: [],
    timeToClose: 50,
    priority: "Medium",
    comments: [
      {
        author: "Charlie Brown",
        datetime: "2025-07-05 14:20",
        text: "Lead registered via contact form.",
      },
    ],
  },
  {
    id: 9,
    leadName: "NextGen Startups",
    leadSource: "Referral",
    assignedAgent: "Bob Williams",
    leadStatus: "Qualified",
    tags: ["High Value"],
    timeToClose: 25,
    priority: "High",
    comments: [
      {
        author: "Bob Williams",
        datetime: "2025-07-03 12:00",
        text: "Scheduled a call to discuss proposal.",
      },
    ],
  },
  {
    id: 10,
    leadName: "EcoGreen Ventures",
    leadSource: "Cold Call",
    assignedAgent: "Alice Johnson",
    leadStatus: "Contacted",
    tags: [],
    timeToClose: 40,
    priority: "Medium",
    comments: [
      {
        author: "Alice Johnson",
        datetime: "2025-07-07 10:10",
        text: "Call made. Sent company brochure.",
      },
    ],
  },
  {
    id: 11,
    leadName: "Apex Fintech",
    leadSource: "Website",
    assignedAgent: "Charlie Brown",
    leadStatus: "Proposal Sent",
    tags: ["Follow-up"],
    timeToClose: 18,
    priority: "High",
    comments: [
      {
        author: "Charlie Brown",
        datetime: "2025-07-06 09:40",
        text: "Sent pricing breakdown via email.",
      },
    ],
  },
  {
    id: 12,
    leadName: "Nova Technologies",
    leadSource: "Referral",
    assignedAgent: "Bob Williams",
    leadStatus: "New",
    tags: [],
    timeToClose: 55,
    priority: "Medium",
    comments: [
      {
        author: "Bob Williams",
        datetime: "2025-07-04 08:30",
        text: "Lead came through client reference.",
      },
    ],
  },
];
