export const LeadData = [
  {
    id: 1,
    name: "Tech Solutions Inc.",
    source: "Website",
    salesAgent: "Alice Johnson",
    status: "New",
    tags: ["High Value"],
    timeToClose: 30,
    priority: "High",
  },
  {
    id: 2,
    name: "Global Innovations Ltd.",
    source: "Referral",
    salesAgent: "Bob Williams",
    status: "Contacted",
    tags: ["Follow-up"],
    timeToClose: 45,
    priority: "Medium",
  },
  {
    id: 3,
    name: "Creative Marketing Agency",
    source: "Cold Call",
    salesAgent: "Alice Johnson",
    status: "Qualified",
    tags: [],
    timeToClose: 20,
    priority: "High",
  },
  {
    id: 4,
    name: "Dynamic Enterprises",
    source: "Website",
    salesAgent: "Charlie Brown",
    status: "Proposal Sent",
    tags: ["High Value", "Follow-up"],
    timeToClose: 15,
    priority: "High",
  },
  {
    id: 5,
    name: "Innovate Solutions LLC",
    source: "Referral",
    salesAgent: "Bob Williams",
    status: "Closed",
    tags: [],
    timeToClose: 10,
    priority: "Low",
  },
  {
    id: 6,
    name: "Pinnacle Consulting",
    source: "Email",
    salesAgent: "Charlie Brown",
    status: "New",
    tags: [],
    timeToClose: 60,
    priority: "Medium",
  },
  {
    id: 7,
    name: "Quantum Tech Group",
    source: "Cold Call",
    salesAgent: "Alice Johnson",
    status: "Contacted",
    tags: ["Follow-up"],
    timeToClose: 35,
    priority: "Low",
  },
  {
    id: 8,
    name: "Bright Future Inc.",
    source: "Website",
    salesAgent: "Charlie Brown",
    status: "New",
    tags: [],
    timeToClose: 50,
    priority: "Medium",
  },
  {
    id: 9,
    name: "NextGen Startups",
    source: "Referral",
    salesAgent: "Bob Williams",
    status: "Qualified",
    tags: ["High Value"],
    timeToClose: 25,
    priority: "High",
  },
  {
    id: 10,
    name: "EcoGreen Ventures",
    source: "Advertisement",
    salesAgent: "Alice Johnson",
    status: "Contacted",
    tags: [],
    timeToClose: 40,
    priority: "Medium",
  },
  {
    id: 11,
    name: "Apex Fintech",
    source: "Website",
    salesAgent: "Charlie Brown",
    status: "Proposal Sent",
    tags: ["Follow-up"],
    timeToClose: 18,
    priority: "High",
  },
  {
    id: 12,
    name: "Nova Technologies",
    source: "Advertisement",
    salesAgent: "Bob Williams",
    status: "New",
    tags: [],
    timeToClose: 55,
    priority: "Medium",
  },
];
